Добавляет разметку главной страницы и каталога
htmlacademy-htmlcss/2267549-device-36 pull request #2
Opened 2023-01-23 22:59 UTC by malyshkinakb

2023-01-24 10:17 UTC, pavel-nyukalo requested changes

2023-01-24 10:17 UTC, pavel-nyukalo commented on index.html
> +            <form class="navigation-user-search" action="https://echo.htmlacademy.ru/" method="post">
Немного отступы поехали. У нас вложенные теги должны быть отделены двумя пробелами, а form от div отделен 4мя

2023-01-24 10:17 UTC, pavel-nyukalo commented on index.html
> +              <input type="search" placeholder="Поиск по сайту">
Давай еще добавим скрытый `label` для инпута

2023-01-24 10:17 UTC, pavel-niukalo commented on index.html
> +      </section>
В слайдер нам нужно так же добавить разметку остальных слайдов

![image](https://user-images.githubusercontent.com/52506235/214264793-9a819977-8065-4c20-9762-8f29b318f259.png)

Но! Нужно учесть то, что кнопки переключения слайдов должны быть прописаны **один** раз - поскольку они относятся ко всему слайдеру, а не к конкретным слайдам

Это я про вот эти

![image](https://user-images.githubusercontent.com/52506235/214264990-04f51b5d-3f09-4f32-97ee-4e9628c78b88.png)

2023-01-24 10:17 UTC, pavel-nyukalo commented on index.html
> +        </div>
Здесь аналогично нужно добавить остальные слайды (и тоже учесть, что список кнопок должен быть прописан один раз

![image](https://user-images.githubusercontent.com/52506235/214265373-a3a38347-2fa7-48d3-bfbf-dc112b9d0b2e.png)

2023-01-24 10:17 UTC, pavel-nyukalo commented on index.html
> +          <input class="field" placeholder="Ваш e-mail" type="email" name="newsletter-email" id="newsletter-email" required>
Тут так же давай добавим скрытый `label`

2023-01-24 10:17 UTC, pavel-nyukalo commented on catalog.html
> +              <input type="search" placeholder="Поиск по сайту">
Аналогичные замечания

2023-01-24 10:17 UTC, pavel-nyukalo commented on catalog.html
> +          <button class="button-show-more" type="button">Загрузить ещЁ</button>
Загрузить ещЁ. Нужно поправить написание

2023-01-24 10:17 UTC, pavel-nyukalo commented on catalog.html
> +        <div class="footer-address">
Тоже отступы нужно поправить

2023-01-25 06:53 UTC, pavel-nyukalo requested changes

2023-01-25 06:53 UTC, pavel-nyukalo commented on index.html
> +            </label>
Здесь нужно быть аккуратным

`visually-hidden` скроет элемент визуально

Соответственно, обернув инпут в `visually-hidden` - он скроется

Тут можно сделать так

```html
<label class="visually-hidden" for="input-id">Поиск по сайту</label>
<input id="input-id" type="search" placeholder="Поиск по сайту">
```

2023-01-25 06:53 UTC, pavel-nyukalo commented on index.html
> +          </label>
Аналогично - инпут скроется. Давай так же рядом сделаем

2023-01-25 06:53 UTC, pavel-nyukalo commented on catalog.html
> +            <input type="search" placeholder="Поиск по сайту">
Здесь тоже нужен `label`

2023-01-25 13:33 UTC, malyshkinakb commented on .vscode/settings.json
> +  "html.format.indentInnerHtml": true,
Не очень поняла, каким образом этот файл изменился...

2023-01-26 12:32 UTC, pavel-nyukalo approved these changes

2023-01-26 12:32 UTC, merged